---
- hosts: coreos
  connection: local
  #gather_facts: false
  tasks:
  - name: Automation CoreOS Cluster
    cloudformation: stack_name='automation-ansible-coreos-cluster' state=present region='us-east-1' disable_rollback=true template='files/stack.json'
    args:
      template_parameters:
        InstanceType: t1.micro
        ClusterSize: 3
        DiscoveryURL: 'https://discovery.etcd.io/'
        KeyPair: Automation
        DockerConfigFile: '{"https://index.docker.io/v1/": {"auth": "","email": "" }}'
    register: stack
    tags:
      Stack: ansible-cloudformation-coreos
